databases:
  - name: shopsync
    plan: free
    databaseName: shopsync
    user: shopsync

services:
  - type: web
    plan: free
    name: ShopSync
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ShopSync.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shopsync
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
