# Generated by Django 5.1.2 on 2024-11-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar5.png', upload_to=''),
        ),
    ]
