# Generated by Django 5.1.2 on 2024-11-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_shop_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
