# Generated by Django 5.1.2 on 2024-11-24 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='image1',
            field=models.ImageField(default='avatar5.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='image2',
            field=models.ImageField(default='avatar5.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='avatar',
            field=models.ImageField(default='avatar5.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_category', to='shop.shopcategory'),
        ),
    ]
