# Generated by Django 5.1.3 on 2025-01-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_is_deleted_shop_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_product_id',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='time_ordered',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='units',
        ),
    ]
