# Generated by Django 5.1.2 on 2024-11-24 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopcategory_shop_image1_shop_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_category', to='shop.shopcategory'),
        ),
    ]
