# Generated by Django 5.1.3 on 2024-12-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='title1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='title2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
