# Generated by Django 5.1.3 on 2025-03-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_shop_avatar3'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='avatar3',
            field=models.ImageField(default='shop3.jpg', upload_to=''),
        ),
    ]
