# Generated by Django 5.1.2 on 2024-11-24 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0013_inventory_discount'),
        ('shop', '0003_alter_shop_shop_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('avatar', models.ImageField(default='avatar5.png', upload_to='')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('units', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('total', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('checked_out', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.inventory')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
    ]
