# Generated by Django 5.1.3 on 2025-01-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cart_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
