# Generated by Django 5.1.2 on 2024-11-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_cart_discount_alter_cart_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='checked_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
