# Generated by Django 5.1.2 on 2024-11-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_timestamp_cart_time_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='order_number',
            new_name='cart_product_id',
        ),
    ]
