# Generated by Django 5.1.3 on 2025-01-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
