# Generated by Django 5.1.2 on 2024-11-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_order_number_cart_cart_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_number',
            field=models.CharField(max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_product_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
