# Generated by Django 5.1.3 on 2025-01-22 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0016_review_email'),
        ('shop', '0009_address_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.coupon'),
        ),
    ]
