# Generated by Django 5.1.2 on 2024-11-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_cart_order_number_alter_cart_cart_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
