# Generated by Django 5.1.2 on 2024-11-25 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_cart_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_number',
        ),
    ]
