# Generated by Django 5.1.3 on 2025-01-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_cart_category_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
