# Generated by Django 5.1.3 on 2025-01-24 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0017_coupon_is_active'),
        ('shop', '0014_alter_cart_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.coupon'),
        ),
    ]
