# Generated by Django 5.1.3 on 2025-02-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_cart_cart_id_cart_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='timestamp',
            new_name='created',
        ),
    ]
