# Generated by Django 5.1.3 on 2025-02-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_rename_timestamp_cart_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(default='processing', max_length=20),
        ),
    ]
