# Generated by Django 5.1.3 on 2025-02-21 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0019_remove_delivery_discount_and_more'),
        ('shop', '0018_alter_cart_status_alter_cartitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dash.inventory'),
        ),
    ]
