# Generated by Django 5.1.3 on 2025-02-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created',
            new_name='timestamp',
        ),
    ]
