# Generated by Django 5.1.3 on 2025-02-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_rename_created_cart_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='dp1',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='dp2',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='dp3',
        ),
        migrations.AddField(
            model_name='shop',
            name='avatar1',
            field=models.ImageField(default='shop1.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='avatar2',
            field=models.ImageField(default='shop2.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='avatar3',
            field=models.ImageField(default='shop13.jpg', upload_to=''),
        ),
    ]
