# Generated by Django 5.1.3 on 2025-02-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_shop_dp1_remove_shop_dp2_remove_shop_dp3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='status',
        ),
    ]
