# Generated by Django 5.1.3 on 2025-03-05 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaysdeal',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='category',
            name='avatar',
            field=models.ImageField(default='category.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='todaysdeal',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='dash.inventory'),
        ),
    ]
