# Generated by Django 5.1.3 on 2025-03-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_remove_todaysdeal_product_id_alter_category_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
