# Generated by Django 5.1.3 on 2025-01-04 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_units_alter_inventory_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='units',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.units'),
        ),
    ]
