# Generated by Django 5.1.3 on 2025-01-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_alter_delivery_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
