# Generated by Django 5.1.2 on 2024-11-22 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_supplier_inventory_supplier'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='shop',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unregistered_user', models.CharField(blank=True, max_length=50, null=True)),
                ('order_number', models.CharField(max_length=12, unique=True)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('units', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('status', models.CharField(default='created', max_length=20)),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_confirmed', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_in_transit', models.DateTimeField(auto_now_add=True, null=True)),
                ('total', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.category')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.inventory')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
