# Generated by Django 5.1.3 on 2024-12-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_helpdesk_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdesk',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
