# Generated by Django 5.1.2 on 2024-11-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_shopstaff_alter_delivery_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='units',
            field=models.CharField(max_length=20),
        ),
    ]
