# Generated by Django 5.1.2 on 2024-11-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_alter_delivery_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
