# Generated by Django 5.1.3 on 2025-01-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_remove_supplier_timestamp_lowstockthreshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='in_orders',
            field=models.BooleanField(default=False),
        ),
    ]
