# Generated by Django 5.1.2 on 2024-11-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_alter_delivery_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='time_confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='time_in_transit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
