# Generated by Django 5.1.3 on 2024-12-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_alter_helpdesk_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='register_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
