# Generated by Django 5.1.3 on 2025-01-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_inventory_in_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='order_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
