# Generated by Django 5.1.2 on 2024-11-23 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_alter_delivery_discount_alter_delivery_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='time_created',
            new_name='timestamp',
        ),
    ]
