# Generated by Django 5.1.3 on 2025-01-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_rename_payment_method_paymentmethod_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaysdeal',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
