# Generated by Django 5.1.3 on 2025-01-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_todaysdeal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaysdeal',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
