# Generated by Django 5.1.3 on 2025-01-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_category_is_deleted_coupon_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='avatar',
        ),
        migrations.AddField(
            model_name='inventory',
            name='avatar1',
            field=models.ImageField(default='pd1.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='inventory',
            name='avatar2',
            field=models.ImageField(default='pd2.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='inventory',
            name='avatar3',
            field=models.ImageField(default='pd3.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='inventory',
            name='avatar4',
            field=models.ImageField(default='pd4.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='inventory',
            name='avatar5',
            field=models.ImageField(default='pd5.jpg', upload_to=''),
        ),
    ]
