# Generated by Django 5.1.2 on 2024-11-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_alter_inventory_price_alter_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_id',
            field=models.CharField(max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
