# Generated by Django 5.1.2 on 2024-11-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0015_inventory_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
