# Generated by Django 5.1.3 on 2025-01-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0016_review_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
