# Generated by Django 5.1.2 on 2024-11-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0016_alter_delivery_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='avatar',
            field=models.ImageField(default='avatar5.png', upload_to=''),
        ),
    ]
