# Generated by Django 5.1.3 on 2025-01-24 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0017_coupon_is_active'),
        ('shop', '0015_cart_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='instructions',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='category',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='county',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='price',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='product',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='total',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='town',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='units',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.address'),
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='dash.delivery')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.inventory')),
            ],
        ),
    ]
