# Generated by Django 5.1.3 on 2025-02-20 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0018_rename_instructions_delivery_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='order_number',
        ),
        migrations.AddField(
            model_name='delivery',
            name='town',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dash.delivery'),
        ),
    ]
