# Generated by Django 5.1.2 on 2024-11-25 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0019_delivery_avatar_alter_category_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='county',
            field=models.CharField(default='Nairobi', max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='town',
            field=models.CharField(default='Nailrobi', max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.paymentmethod'),
        ),
    ]
