# Generated by Django 5.1.3 on 2025-02-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0019_remove_delivery_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='avatar',
            field=models.ImageField(default='shop1.jpg', upload_to=''),
        ),
    ]
