# Generated by Django 5.1.2 on 2024-11-26 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0020_paymentmethod_delivery_county_delivery_town_and_more'),
        ('shop', '0011_remove_cart_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
    ]
