# Generated by Django 5.1.3 on 2025-02-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0020_delivery_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
