# Generated by Django 5.1.3 on 2025-02-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0021_delivery_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
