# Generated by Django 5.1.2 on 2024-11-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0022_alter_paymentmethod_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order_number',
            field=models.CharField(max_length=10),
        ),
    ]
