# Generated by Django 5.1.3 on 2025-02-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0022_delivery_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='time_in_transit',
            new_name='time_shipped',
        ),
    ]
