# Generated by Django 5.1.2 on 2024-11-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0023_alter_delivery_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='source',
            field=models.CharField(default='dash', max_length=10),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(default='processing', max_length=20),
        ),
    ]
